Fixed bone-headed bugs in with ballistics
Bugs Fixed include:
    - NullPointerException in BallisticArcSelection.first() and last()
    - NoSuchMethodError when trying to call skipNBytes
    - Incorrect skipped amount when reading velocity in arc streams

On top of this, performance of reading arcs was greatly improved, as
arcs' individual points no longer has to be read and written.